/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package milktea.ordering.system;
import javax.swing.JOptionPane;

/**
 *
 * @author SquidGame
 */
public class Milktea extends javax.swing.JFrame {

    /**
     * Creates new form Milktea
     */
    public Milktea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        m3 = new javax.swing.JCheckBox();
        m4 = new javax.swing.JCheckBox();
        m5 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        m2 = new javax.swing.JCheckBox();
        m1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        q3 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        dine = new javax.swing.JRadioButton();
        takeOut = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPrefer = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        q1 = new javax.swing.JSpinner();
        q2 = new javax.swing.JSpinner();
        q4 = new javax.swing.JSpinner();
        q5 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rS1 = new javax.swing.JRadioButton();
        rM1 = new javax.swing.JRadioButton();
        rS2 = new javax.swing.JRadioButton();
        rM2 = new javax.swing.JRadioButton();
        rS3 = new javax.swing.JRadioButton();
        rM3 = new javax.swing.JRadioButton();
        rS4 = new javax.swing.JRadioButton();
        rM4 = new javax.swing.JRadioButton();
        rS5 = new javax.swing.JRadioButton();
        rM5 = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnCal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(94, 77, 46));

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WANS MILKTEA");

        jPanel2.setBackground(new java.awt.Color(56, 40, 30));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 28, 15), 10, true));

        m3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        m3.setForeground(new java.awt.Color(255, 255, 255));
        m3.setText("Red Velvet");
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });

        m4.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        m4.setForeground(new java.awt.Color(255, 255, 255));
        m4.setText("Taro");
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });

        m5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        m5.setForeground(new java.awt.Color(255, 255, 255));
        m5.setText("Okinawa");
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("P 29.-00");

        jLabel10.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("P 29.-00");

        jLabel11.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("P 29.-00");

        jLabel12.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("P 29.-00");

        jLabel13.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("P 29.-00");

        jLabel14.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("P 39.00");

        jLabel15.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("P 39.00");

        jLabel16.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("P 39.00");

        jLabel17.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("P 39.00");

        jLabel18.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("P 39.00");

        jLabel3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Medium");

        jLabel7.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Small");

        m2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 255, 255));
        m2.setText("Cookies n Cream");
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        m1.setBackground(new java.awt.Color(255, 255, 255));
        m1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setText("Matcha");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milktea/images/girl.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milktea/images/boy.png"))); // NOI18N
        jLabel25.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(30, 30, 30))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(188, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(111, 111, 111)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(m1))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14)
                    .addComponent(m2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m5)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel7)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );

        q3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        q3.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price & Size");

        btnOrder.setBackground(new java.awt.Color(40, 90, 39));
        btnOrder.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setText("ORDER");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 57, 48), 10));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel3.setBackground(new java.awt.Color(56, 39, 21));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(80, 57, 48), 5, true));

        buttonGroup2.add(dine);
        dine.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        dine.setForeground(new java.awt.Color(255, 255, 255));
        dine.setText("Dine in");
        dine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineActionPerformed(evt);
            }
        });

        buttonGroup2.add(takeOut);
        takeOut.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        takeOut.setForeground(new java.awt.Color(255, 255, 255));
        takeOut.setText("Take out");
        takeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dine, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(takeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dine)
                    .addComponent(takeOut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(44, 41, 35));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 57, 48), 10));

        jLabel8.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prefer to:");

        jPrefer.setEditable(false);
        jPrefer.setBackground(new java.awt.Color(2, 3, 4));
        jPrefer.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jPrefer.setForeground(new java.awt.Color(255, 255, 255));
        jPrefer.setMargin(new java.awt.Insets(0, 20, 0, 0));
        jPrefer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPreferActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Total:");

        jTotal.setEditable(false);
        jTotal.setBackground(new java.awt.Color(2, 3, 4));
        jTotal.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTotal.setMargin(new java.awt.Insets(0, 20, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jTotal))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPrefer, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPrefer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Costumers Order");

        jLabel21.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Option");

        q1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        q1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        q2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        q2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        q4.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        q4.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        q5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        q5.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel22.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Small");

        jLabel23.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Medium");

        jLabel4.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu");

        jPanel5.setBackground(new java.awt.Color(39, 33, 17));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(80, 57, 48), 5, true));

        buttonGroup3.add(rS1);

        buttonGroup3.add(rM1);
        rM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rM1ActionPerformed(evt);
            }
        });

        buttonGroup4.add(rS2);

        buttonGroup4.add(rM2);
        rM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rM2ActionPerformed(evt);
            }
        });

        buttonGroup5.add(rS3);

        buttonGroup5.add(rM3);
        rM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rM3ActionPerformed(evt);
            }
        });

        buttonGroup6.add(rS4);

        buttonGroup6.add(rM4);
        rM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rM4ActionPerformed(evt);
            }
        });

        buttonGroup7.add(rS5);

        buttonGroup7.add(rM5);
        rM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rM5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rS5)
                        .addGap(45, 45, 45)
                        .addComponent(rM5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rS3)
                        .addGap(45, 45, 45)
                        .addComponent(rM3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rS4)
                        .addGap(45, 45, 45)
                        .addComponent(rM4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rS2)
                        .addGap(45, 45, 45)
                        .addComponent(rM2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rS1)
                        .addGap(45, 45, 45)
                        .addComponent(rM1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rS1)
                    .addComponent(rM1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rS2)
                    .addComponent(rM2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rS3)
                    .addComponent(rM3))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rS4)
                    .addComponent(rM4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rS5)
                    .addComponent(rM5))
                .addContainerGap())
        );

        btnClear.setBackground(new java.awt.Color(138, 51, 51));
        btnClear.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milktea/images/wow.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel26.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Quantity");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milktea/images/wans-removebg-preview.png"))); // NOI18N
        jLabel24.setText("jLabel24");

        btnCal.setBackground(new java.awt.Color(27, 27, 85));
        btnCal.setFont(new java.awt.Font("Bradley Hand ITC", 1, 14)); // NOI18N
        btnCal.setForeground(new java.awt.Color(255, 255, 255));
        btnCal.setText("CALCULATE");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCal)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(220, 220, 220)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGap(12, 12, 12)
                                                            .addComponent(jLabel26)))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jLabel22)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jLabel23))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(24, 24, 24)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(929, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jLabel4)
                    .addContainerGap(557, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m3ActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m4ActionPerformed

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m5ActionPerformed

    private void dineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dineActionPerformed

    private void takeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_takeOutActionPerformed

    private void rM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rM2ActionPerformed

    private void rM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rM3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rM3ActionPerformed

    private void rM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rM4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rM4ActionPerformed

    private void rM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rM5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rM5ActionPerformed

    private void rM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rM1ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m2ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m1ActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        String display  =  "";
        String display2 =  "";
        String display3 =  "";
        String display4 =  "";
        String display5 =  "";
        

       
      //Display dine in or Take out
        String dPrefer =  "";
        //for button
        rS1.setActionCommand("Small");
        rS2.setActionCommand("Small");
        rS3.setActionCommand("Small");
        rS4.setActionCommand("Small");
        rS5.setActionCommand("Small");

        rM1.setActionCommand("Medium");
        rM2.setActionCommand("Medium");
        rM3.setActionCommand("Medium");
        rM4.setActionCommand("Medium");
        rM5.setActionCommand("Medium");

        dine.setActionCommand("Dine in");
        takeOut.setActionCommand("Take Out");
        int quan1 = (int) q1.getValue();
        int quan2 = (int) q2.getValue();
        int quan3 = (int) q3.getValue();
        int quan4 = (int) q4.getValue();
        int quan5 = (int) q5.getValue();

        int []price = {0,29,39};

        //Calculate total it defends the quantity of every selected milktea
        int total = price[0] * quan1;
        int total2 = price[0] * quan2;
        int total3 = price[0] * quan3;
        int total4 = price[0] * quan4;
        int total5 = price[0] * quan5;

        //This is for small selecet
        if (rS1.isSelected() && m1.isSelected()) {
            total = price[1] * quan1;
            display += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m1.getText() + "\n"
            + " Size: " + rS1.getActionCommand()+"\n"
            +"Total of Order: "+ q1.getValue()+"\n";
            JOptionPane.showMessageDialog(this, "Naks marunong ng omorder si tanga");
     
          
        }
        else if (rS1.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }
        
        if (rS2.isSelected() && m2.isSelected()) {
            total2 = price[1] * quan2;
            display2 += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m2.getText() + "\n"
            + " Size: " + rS1.getActionCommand()+"\n"
            +"Total of Order: "+ q2.getValue()+"\n";
            
           
        }
        else if (rS2.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }
        if (rS3.isSelected() && m3.isSelected()) {
            total3 = price[1] * quan3;
            display3 += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m3.getText() + "\n"
            + " Size: " + rS1.getActionCommand()+"\n"
           +"Total of Order: "+ q3.getValue()+"\n";
        }
        else if (rS3.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }
        if (rS4.isSelected() && m4.isSelected()) {
            total4 = price[1] * quan4;
            display4 += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m4.getText() + "\n"
            + " Size: " + rS4.getActionCommand()+"\n"
           +"Total of Order: "+ q4.getValue()+"\n";
        }
        else if (rS4.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }
        if (rS5.isSelected() && m5.isSelected()) {
            total5 = price[1] * quan5;
            display5 += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m5.getText() + "\n"
            + " Size: " + rS5.getActionCommand()+"\n"
            +"Total of Order: "+ q5.getValue()+"\n";
        }
        else if (rS5.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }

        //If Medium is Selected
        if (rM1.isSelected() && m1.isSelected()) {
            total = price[2] * quan1;
            display += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m1.getText() + "\n"
            + " Size: " + rM1.getActionCommand()+"\n"
            +"Total of Order: "+ q1.getValue()+"\n";
        }
        else if (rM1.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }
        if (rM2.isSelected() && m2.isSelected()) {
            total2 = price[2] * quan2;
            display2 += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m2.getText() + "\n"
            + " Size: " + rM2.getActionCommand()+"\n"
            +"Total of Order: "+ q2.getValue()+"\n";
        }
        else if (rM2.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }
        if (rM3.isSelected() && m3.isSelected()) {
            total3 = price[2] * quan3;
            display3 += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m3.getText() + "\n"
            + " Size: " + rM3.getActionCommand()+"\n"
            +"Total of Order: "+ q3.getValue()+"\n";
        }
        else if (rM3.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }
        if (rM4.isSelected() && m4.isSelected()) {
            total4 = price[2] * quan4;
            display4 += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m4.getText() + "\n"
            + " Size: " + rM4.getActionCommand()+"\n"
            +"Total of Order: "+ q4.getValue()+"\n";
        }
        else if (rM4.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }
        if (rM5.isSelected() && m5.isSelected()) {
            total5 = price[2] * quan5;
            display5 += "Name: " + CustomerName.cname.getText() + "\n"
            + " Milktea: " + m5.getText() + "\n"
            + " Size: " + rM5.getActionCommand()+"\n"
            +"Total of Order: "+ q5.getValue()+"\n";
        }
        else if (rM5.isSelected()) {
            JOptionPane.showMessageDialog(this, "No Menu Selected");
            return;
        }

        // Check if "Dine in" or "Take Out" is selected and add it to the display
        if (dine.isSelected()) {
            dPrefer += "\nDine in";
        } else if (takeOut.isSelected()) {
            dPrefer += "\nTake Out";

        }

        //total
        jTotal.setText(String.valueOf(total + total2 + total3 + total4 + total5));

        //Display every Seleced Milktea
        jTextArea2.setText(display+display2+display3+display4+display5);

        //for take out and dine in
        jPrefer.setText(dPrefer);
   

    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        // TODO add your handling code here:
        Calculate cal = new Calculate();
       cal.jPrefer2.setText(jTotal.getText());
        cal.setVisible(true);
       
        
    }//GEN-LAST:event_btnCalActionPerformed

    private void jPreferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPreferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPreferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Milktea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Milktea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Milktea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Milktea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Milktea().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnOrder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JRadioButton dine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jPrefer;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    public static javax.swing.JTextField jTotal;
    private javax.swing.JCheckBox m1;
    private javax.swing.JCheckBox m2;
    private javax.swing.JCheckBox m3;
    private javax.swing.JCheckBox m4;
    private javax.swing.JCheckBox m5;
    private javax.swing.JSpinner q1;
    private javax.swing.JSpinner q2;
    private javax.swing.JSpinner q3;
    private javax.swing.JSpinner q4;
    private javax.swing.JSpinner q5;
    private javax.swing.JRadioButton rM1;
    private javax.swing.JRadioButton rM2;
    private javax.swing.JRadioButton rM3;
    private javax.swing.JRadioButton rM4;
    private javax.swing.JRadioButton rM5;
    private javax.swing.JRadioButton rS1;
    private javax.swing.JRadioButton rS2;
    private javax.swing.JRadioButton rS3;
    private javax.swing.JRadioButton rS4;
    private javax.swing.JRadioButton rS5;
    private javax.swing.JRadioButton takeOut;
    // End of variables declaration//GEN-END:variables
}
